version: '3.8'

services:
  backend:
    build:
      context: ./backend  # Chemin vers le répertoire du backend Go
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - mynetwork

  frontend:
    build:
      context: ./frontend  # Chemin vers le répertoire du frontend Next.js
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge